# Generated by Django 3.2.7 on 2021-10-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_data_nasc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
    ]
